### PR TITLE
modify straight logic and keyboard behavior

### PR DESCRIPTION
**Pull request by SilkSong**
It seems that there is a typo in straight logic when gender is female and straight is on, the interest should be men, right? And also modify the keyboard behavior to dismiss the keyboard when tapping anywhere on view controller and auto move up textField when keyboard is present.

### CODE REVIEW

**Comment by soapyigu** [comment]
I notice there are a lot of files changed. Why adding a new TODO and with a lot of image assets?

**Comment by SilkSong** [comment]
Oh， I am sorry I am new to github work flow. Actually I want to flow your repo to learn iOS and practice. So the new ToDo is my own project. It should be removed from the pull request it seems. As for the pull request, is fully depend on the tweet project. Can you just update the tweet project ?

2017年8月14日 +0800 08:14 Yi <notifications@github.com>，写道：

**Comment by SilkSong** [comment]
And I noticed that in your ToDo App, if deleted all the items, the no item screen will be shown, but if you try to add item later, that screen will not dismiss. Because I fully achieve the app myself not following your code, so that the way I realized that functions is totally different form yours. so that I did not want to make a pull request for the ToDo. But hope you can fix that bug.

2017年8月14日 +0800 08:14 Yi <notifications@github.com>，写道：

**Comment by soapyigu** [comment]
There is a merge conflict, could you please resolve it at first?

**Pull request closed without merging**
